### ISSUE TITLE
pictures missing after restart

### ISSUE THREAD

**Issue by subzer047** [dnhsoft/docker-shopware#1]
after running restart-containers.sh all pictures in media directory are missing
actually I use SW 5.2.20 with php7 but I had this problem already since 5.2.12

**Comment by chudomir-delchev-dnh** [comment]
Hello - I guess you need to mount the directories.

In local or production development we always create volumes for certain Shopware directories.
Here are the volumes from a sample docker-file: 

  volumes:
   - ".log:/shopware/var/log"
   - ".files:/shopware/files"
   - ".media:/shopware/media"
   - ".community-plugins:/shopware/engine/Shopware/Plugins/Community"
   - ".cache/:/shopware/web/cache/"


Then even when you remove the image, you will have the log, the files and media and the downloaded community plugins.

**Comment by subzer047** [comment]
Great Idea to mount the media directory!
I didn't think about that way.

Thank you!

**Comment by chudomir-delchev-dnh** [comment]
No probs :)
Sometimes, when you use mounted directories, you may have a problem with their rights inside the container. 
I.e. if you go into the container shell, they will not be owned by www-data.

If this happens, simply call /swtools/prepare-dirs.sh inside the container. 

or docker-compose exec shop /swtools/prepare-dirs.sh
