### ISSUE TITLE
Dockerfile 5.6.0 not working

### ISSUE THREAD

**Issue by lordofthebrain** [dnhsoft/docker-shopware#8]
Shopware 5.6 need php 7.2 or higher. Base image runs with php 7.0

**Comment by lordofthebrain** [comment]
Add the following lines to the Dokerfile after the FROM line:

RUN apt-get update \
    && apt -y install lsb-release apt-transport-https ca-certificates \
    && wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg \
    &&  echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/php7.3.list \
    && apt-get update \
    && apt-get -y install php7.3 \
    && apt-get -y install php7.3-mysql \
    && apt-get -y install php7.3-xml \
    && apt-get -y install php7.3-curl \
    && apt-get -y install php7.3-zip \
    && apt-get -y install php7.3-gd \
    && apt-get -y install php7.3-common \
    && apt-get -y install php7.3-mbstring \
    && apt-get -y install php7.3-json \
    && cp /usr/bin/php /usr/local/bin \
    && a2enmod php7.3

Build the images and shopware 5.6 now works.

**Comment by xndrdev** [comment]
There's a simpler way. Just build with the version variable: 
```docker build --build-arg SHOPWARE_VERSION=latest -t dnhsoft/shopware:5.6.1-php7 .```

**Comment by mkafadarov** [comment]
Sorry for the long delay, shopware 5.6.0 image is now fixed
