### ISSUE TITLE
Shopware 5.6.2 is missing

### ISSUE THREAD

**Issue by iocron** [dnhsoft/docker-shopware#9]
There is currently no image for shopware 5.6.2 (this one is quite important because of many bugfixes). Also the latest version in download-shopware.sh is only shopware 5.6.1.

**Comment by mkafadarov** [comment]
shopware 5.6.2 added

**Comment by iocron** [comment]
Error response from daemon: manifest for dnhsoft/shopware:5.6.3 not found: manifest unknown: manifest unknown

Same goes for 5.6.2. Can't pull the images (from docker hub) due to the error above (5.6.1 is still working).

P.S. The repo https://github.com/dnhsoft/sw-docker-demo/ also still has the old examples with 5.6.1

**Comment by mkafadarov** [comment]
fixed
